services:
  - type: web
    name: n8n-whatsapp-agent
    env: docker

    dockerImage:
      url: docker.n8n.io/n8nio/n8n

    plan: free
    region: singapore

    envVars:
      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      - key: N8N_SECURE_COOKIE
        value: "false"

      - key: N8N_RUNNERS_ENABLED
        value: "true"

      - key: N8N_ENCRYPTION_KEY
        sync: false

      # PostgreSQL
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        value: aws-1-ap-southeast-2.pooler.supabase.com

      - key: DB_POSTGRESDB_PORT
        value: 5432

      - key: DB_POSTGRESDB_DATABASE
        value: postgres

      - key: DB_POSTGRESDB_USER
        value: postgres.lobldvmbhodcyydgylal

      - key: DB_POSTGRESDB_PASSWORD
        sync: false

      - key: DB_POSTGRESDB_SCHEMA
        value: n8n